# Generated by Django 5.0.3 on 2024-03-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_teachers_remove_student_video_student_city_and_more'),
        ('teacher', '0004_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='myapp.student'),
        ),
    ]
