# Generated by Django 5.0.3 on 2024-03-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
