# Generated by Django 5.0.3 on 2024-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
