# Generated by Django 5.0.3 on 2024-03-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
