# Generated by Django 5.0.3 on 2024-03-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='video',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='uniqueid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
