# Generated by Django 5.0.3 on 2024-03-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_teachers_remove_student_video_student_city_and_more'),
        ('teacher', '0006_remove_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='teacher.course'),
        ),
    ]
